import { createConstants } from '../utils';

export default createConstants(
    'ALUMNI_FETCH_REQUEST',
    'ALUMNI_FETCH_SUCCESS',
    'ALUMNI_FETCH_FAILURE',

    'ALUMNI_PENDING_FETCH_REQUEST',
    'ALUMNI_PENDING_FETCH_SUCCESS',
    'ALUMNI_PENDING_FETCH_FAILURE',

    'ALUMNI_UPDATE',
    'ALUMNI_FILTER_UPDATE',
    'ALUMNI_RESET',

    'AUTH_FETCH_REQUEST',
    'AUTH_FETCH_SUCCESS',
    'AUTH_FETCH_FAILURE',

    'REGISTER_FETCH_REQUEST',
    'REGISTER_FETCH_SUCCESS',
    'REGISTER_FETCH_FAILURE',

    'PROFILE_FETCH_REQUEST',
    'PROFILE_FETCH_SUCCESS',
    'PROFILE_FETCH_FAILURE',
    'PROFILE_UPDATE_SUCCESS',
    'PROFILE_UPDATE_FAILURE',

    'AUTH_RESET',
    'CHAT_USER_UPDATE',
    'ARRAY_USERS',
);