import { createConstants } from '../utils';

export default createConstants(
    'ALUMNI_FETCH_REQUEST',
    'ALUMNI_FETCH_SUCCESS',
    'ALUMNI_FETCH_FAILURE',
    'ALUMNI_UPDATE',
    'ALUMNI_RESET',

    'AUTH_FETCH_REQUEST',
    'AUTH_FETCH_SUCCESS',
    'AUTH_FETCH_FAILURE',

    'REGISTER_FETCH_REQUEST',
    'REGISTER_FETCH_SUCCESS',
    'REGISTER_FETCH_FAILURE',

    'AUTH_RESET',
    'CHAT_USER_UPDATE',
);